# Travis-CI script to install & test MOOSE with NeuroML

dist: bionic
sudo: true  

addons:
  apt:
    packages:
    - libhdf5-dev
    - python-dev
    - python-numpy
    - libhdf5-dev
    - cmake 
    - libgsl0-dev 
    - python-matplotlib 
    - python-scipy 
    - python-lxml
    - g++

language: python

python: 
  #- "2.7" # would be nice if it worked, but not essential
  - "3.6"



install:  
  - pip install scipy # Why is this needed? Doesn't seem to get installed correctly on trusty with addons above...
  - pip install matplotlib # Why is this needed? Doesn't seem to get installed correctly on trusty with addons above...
  
  - pip install pyneuroml
  - pip freeze

  
  - git clone https://github.com/BhallaLab/moose-core.git ####### BhallaLab!!!!
  - cd moose-core
  - git checkout master
  - mkdir build_
  - cd build_
  - which python
  - cmake -DDEBUG=ON -DCMAKE_INSTALL_PREFIX=/usr -DPYTHON_EXECUTABLE=`which python` ..
  - make -j4
  - sudo make install
  - ls -alt
  - cd python
  - sudo `which python` setup.py install
  - cd ../../..
  - pwd
  - ls -alth
  - pip freeze



script:
  - ./test.sh
  - cd NeuroML/GranuleCell
  - python Granule98.py -nogui
  - cd ../../moose-core/python/moose/neuroml2
  - python run_cell.py -nogui

