# Travis-CI script to install & test MOOSE with NeuroML

dist: xenial
sudo: true  

addons:
  apt:
    packages:
    - libhdf5-dev
    - python-dev
    - python-numpy
    - libhdf5-dev
    - cmake 
    - libgsl0-dev 
    - python-matplotlib 
    - python-scipy 
    - python-lxml
    - g++

language: python
python: 
  - "2.7"
  - "3.5"
  #- "3.6"  ## Moose doesn't build correctly?
  - "3.7"



install:
  - wget http://download.opensuse.org/repositories/home:moose/xUbuntu_14.04/Release.key
  - sudo apt-key add - < Release.key  
  - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/moose/xUbuntu_14.04/ /' >> /etc/apt/sources.list.d/moose.list"
  - # sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/moose/xUbuntu_16.04/ /' > /etc/apt/sources.list.d/pymoose.list"
  - sudo apt-get update
  - sudo apt-get install pymoose # use just python scripting.
  - sudo apt-get install -y python-matplotlib python-scipy python-networkx python-pip
  - sudo pip install libneuroml pyneuroml 
  - sudo pip install python-libsbml

script:
  - ./test.sh
  - cd NeuroML/GranuleCell && python Granule98.py -nogui
  - cd ../ && python run_cell.py -nogui
