# Travis-CI script to install & test MOOSE with NeuroML

dist: trusty
sudo: true  

addons:
  apt:
    packages:
    - libhdf5-dev
    - python-dev
    - python-numpy
    - libhdf5-dev
    - cmake 
    - libgsl0-dev 
    - g++

language: python
python: 2.7

virtualenv:
system_site_packages: true


install:
  - git clone https://github.com/pgleeson/moose-core.git ####### pgleeson!!!!
  - cd moose-core
  - mkdir build_
  - cd build_
  - which python
  - cmake -DDEBUG=ON -DQUIET_MODE=ON -DPYTHON_EXECUTABLE="/home/travis/virtualenv/python2.7.13/bin/python" ..
  - make
  - sudo make install
  - ls -alt
  - cd python
  - sudo /home/travis/virtualenv/python2.7.13/bin/python setup.py install
  - cd ../../..
  - pwd
  - ls -alth


script:
  - ./test.sh
  - cd NeuroML/GranuleCell
  - python Granule98.py -nogui
  - cd ../../moose-core/python/moose/neuroml2
  - python run_cell.py -nogui

