# Travis-CI script to install & test MOOSE with NeuroML

install:
  - apt-get  install libhdf5-dev
  - git clone https://github.com/BhallaLab/moose-core.git
  - cd moose-core
  - mkdir build_
  - cd build_
  - cmake ..
  - make


script:
  - ./test.sh
  - cd NeuroML/GranuleCell
  - python Granule98.py -nogui

