# Travis-CI script to install & test MOOSE with NeuroML

install:
  - wget http://download.opensuse.org/repositories/home:moose/xUbuntu_14.04/Release.key
  - sudo apt-key add - < Release.key  
  - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/moose/xUbuntu_14.04/ /' >> /etc/apt/sources.list.d/moose.list"
  - sudo apt-get update
  - sudo apt-get install moose 

script:
  - ./test.sh
  - cd NeuroML/GranuleCell
  - python Granule98.py -nogui
