# Travis-CI script to install & test MOOSE with NeuroML

install:

  - sudo apt-get install libhdf5-serial-dev  # explicitly installing this package
  - sudo apt-get install libgsl0-dev         # explicitly installing this package
  - sudo apt-get install libgsl0ldbl         # explicitly installing this package
  #- sudo -E ./ubuntu-dep.sh
  - sudo -E add-apt-repository ppa:bhallalab/moose
  - sudo apt-get update
  - sudo apt-get install moose-python

script:

  - ls -alt
