# Travis-CI script to install & test MOOSE with NeuroML

install:

  - sudo add-apt-repository -y ppa:bhallalab/moose
  - sudo apt-get update
  - sudo apt-get install moose-python  moose-gui  moose-moogli

script:
  - pwd
  - ls -alt
  - python test.py

