# Travis-CI script to install & test MOOSE with NeuroML

dist: xenial
sudo: true  

addons:
  apt:
    packages:
    - libhdf5-dev
    - python-dev
    - python-numpy
    - libhdf5-dev
    - cmake 
    - libgsl0-dev 
    - python-matplotlib 
    - python-scipy 
    - python-lxml
    - g++

language: python
python: 
  - "2.7"
  - "3.5"
  - "3.6"



install:  
  - pip install scipy # Why is this needed? Doesn't seem to get installed correctly on trusty with addons above...
  - pip install matplotlib # Why is this needed? Doesn't seem to get installed correctly on trusty with addons above...
  
  - pip install libneuroml
  - git clone https://github.com/NeuroML/pyNeuroML.git ## use very latest
  - cd pyNeuroML
  - python setup.py install
  - cd ..
  
  - git clone https://github.com/pgleeson/moose-core.git ####### pgleeson!!!!
  - cd moose-core
  - mkdir build_
  - cd build_
  - which python
  - cmake -DDEBUG=ON -DQUIET_MODE=ON -DPYTHON_EXECUTABLE=`which python` ..
  - make
  - sudo make install
  - ls -alt
  - cd python
  - sudo `which python` setup.py install
  - cd ../../..
  - pwd
  - ls -alth



script:
  - ./test.sh
  - cd NeuroML/GranuleCell
  - python Granule98.py -nogui
  - cd ../../moose-core/python/moose/neuroml2
  - python run_cell.py -nogui

