name: Build from GitHub - OSB

on:
  push:
    branches: [ master, dev* , test* ]
  pull_request:
    branches: [ master, dev* , test* ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}
        

    - name: Install OMV
      run: |
        pip install git+https://github.com/OpenSourceBrain/osb-model-validation
        
    - name: Install Moose from GitHub
      run: |

        git clone https://github.com/BhallaLab/moose-core.git
        cd moose-core
        git checkout master

        pip install jupyter
        pip install jupyter_packaging
        pip install scipy
        pip install pyneuroml
        pip install pybind11[global]
        pip install python-libsbml
        
        sudo apt-get install libhdf5-dev
        
        pip install .

        pip list
        
        echo "MOOSE version:"
        python -c "import moose; print(moose.__version__)"

    - name: Test Moose files
      run: |
        python tests/python/test_function.py
        #./test.sh

    - name: Test simple Moose file
      run: |
        cd NeuroML2
        python -c "import moose; print(moose.__version__)"
        echo "Running simple file"
        python simple.py

        echo "Running NeuroML 2 file"
        python run_hhcell.py -nogui


    - name: Test OMV on Moose
      run: |
        cd NeuroML2/test_files
        omv all --engine=jNeuroML_Moose


    - name: Final version info
      run: |
        omv list -V 
