

name: Test with Moose stable via pip

on:
  push:
    branches: [ master, dev* , test*, experimental ]
  pull_request:
    branches: [ master, dev* , test*, experimental ]

jobs:
  build:

    name: PyPI test for Python v${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.9, "3.10" ]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}


    - name: Install Moose
      run: |

        pip install pyneuroml scipy # missing(?) dependencies

        pip install pymoose
        pip list

    - name: Test Moose files
      run: |
        python tests/python/test_function.py
        #./test.sh

    - name: Test simple Moose file
      run: |
        cd NeuroML
        python -c "import moose; print(moose.__version__)"
        echo "Running simple file"
        python simple.py


    - name: Test Moose files with NeuroML version 2
      run: |
        cd NeuroML
        python run_hhcell.py -nogui

    - name: Final version info
      run: |
        pip list
